dist: focal
language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls
  - pip install pyyaml

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_success:
  - coverage report
  - coveralls --service=travis-ci --branch=main

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "mysite"
  env: "mysite-henry"
  bucket_name: "elasticbeanstalk-us-east-1-783764589295"
  bucket_path: "mysite"
  on:
    repo: "07653/SWE-HW2"
    branch: main

